spring.application.name=findmytutor-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/findmytutor
spring.datasource.username=postgres
spring.datasource.password=root7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true